/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/voice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/asr/asr.contract`; params?: Router.UnknownInputParams; } | { pathname: `/asr/asr.errors`; params?: Router.UnknownInputParams; } | { pathname: `/asr/expoSpeechRecognizer`; params?: Router.UnknownInputParams; } | { pathname: `/services/voice`; params?: Router.UnknownInputParams; } | { pathname: `/components/VoiceRecorder`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/voice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/asr/asr.contract`; params?: Router.UnknownOutputParams; } | { pathname: `/asr/asr.errors`; params?: Router.UnknownOutputParams; } | { pathname: `/asr/expoSpeechRecognizer`; params?: Router.UnknownOutputParams; } | { pathname: `/services/voice`; params?: Router.UnknownOutputParams; } | { pathname: `/components/VoiceRecorder`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/voice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/asr/asr.contract${`?${string}` | `#${string}` | ''}` | `/asr/asr.errors${`?${string}` | `#${string}` | ''}` | `/asr/expoSpeechRecognizer${`?${string}` | `#${string}` | ''}` | `/services/voice${`?${string}` | `#${string}` | ''}` | `/components/VoiceRecorder${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/voice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/asr/asr.contract`; params?: Router.UnknownInputParams; } | { pathname: `/asr/asr.errors`; params?: Router.UnknownInputParams; } | { pathname: `/asr/expoSpeechRecognizer`; params?: Router.UnknownInputParams; } | { pathname: `/services/voice`; params?: Router.UnknownInputParams; } | { pathname: `/components/VoiceRecorder`; params?: Router.UnknownInputParams; };
    }
  }
}
